train:
	python main.py --train --model_name $(MODEL_NAME) --glove_file $(GLOVE_FILE) --code_book_len $(M) --cluster_num $(K)

evluate:
	python main.py --evalutate --model_name $(MODEL_NAME) --glove_file $(GLOVE_FILE)



