train:
	python main.py --train --model_name $(MODEL_NAME) --glove_file $(GLOVE_FILE) --code_book_len $(M) --cluster_num $(K)

evaluate:
	python main.py --evaluate --model_name $(MODEL_NAME) --glove_file $(GLOVE_FILE)



